apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-exporter-secret
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/Ndomi-Nqeketo/platform_engineer_project.git
    targetRevision: masters
    path: applications/postgres-exporter
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true