apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - ../../../../applications/postgres-exporter/external-secret.yaml
  - external-secret-application.yaml