apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterhub-backend
  namespace: masterhub
  labels:
    app: masterhub-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: masterhub-backend
  template:
    metadata:
      labels:
        app: masterhub-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: backend
          image: ndomi/mastershub-backend:latest
          imagePullPolicy: Always
          
          envFrom:
            - secretRef:
                name: masterhub-postgres
            - secretRef:
                name: masterhub-minio
          env:
            - name: MINIO_ENDPOINT
              value: minio.minio.svc.cluster.local
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_BUCKET
              value: masterhub
            - name: MINIO_USE_SSL
              value: "false"
          
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"