apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: monitoring
spec:
  gatewayClassName: traefik
  listeners:
    - name: websecure
      protocol: HTTPS
      port: 443
      hostname: prometheus.ndomi.local
      tls:
        mode: Terminate
        certificateRefs:
          - name: prometheus-tls
            group: ""
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Same
