apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://kubernetes-sigs.github.io/descheduler/
    chart: descheduler
    targetRevision: 0.33.0
    helm:
      releaseName: descheduler
      values: |
        deschedulerPolicy:
          profiles:
            - name: default
        
              pluginConfig:
                - name: DefaultEvictor
                  args:
                    nodeFit: true
        
                - name: RemovePodsViolatingNodeAffinity
                  args:
                    nodeAffinityType:
                      - requiredDuringSchedulingIgnoredDuringExecution
        
                - name: RemovePodsViolatingInterPodAntiAffinity
        
                - name: LowNodeUtilization
                  args:
                    thresholds:
                      cpu: 15
                      memory: 15
                      pods: 20
                    targetThresholds:
                      cpu: 40
                      memory: 40
                      pods: 50
        
              plugins:
                balance:
                  enabled:
                    - LowNodeUtilization
        
                deschedule:
                  enabled:
                    - RemovePodsViolatingNodeAffinity
                    - RemovePodsViolatingInterPodAntiAffinity
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    syncOptions:
      - CreateNamespace=true