service:
  type: ClusterIP
  port: 80

serviceMonitor:
  enabled: true
  labels:
    release: prometheus

persistence:
  enabled: true
  type: pvc
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  size: 5Gi

initChownData:
  enabled: false
  
admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

grafana.ini:
  server:
    domain: grafana.ndomi.local
    root_url: https://grafana.ndomi.local

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true

sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true
    
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m
