apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.1.4
      helm:
        releaseName: grafana
        valueFiles:
          - $values/infrastructure/argocd/base/grafana/grafana-values.yaml
          -
    - repoURL: https://github.com/Ndomi-Nqeketo/platform_engineer_project.git
      targetRevision: masters
      ref: values

    - repoURL: https://github.com/Ndomi-Nqeketo/platform_engineer_project.git
      targetRevision: masters
      path: infrastructure/monitoring/grafana
      
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
