apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: vault
    namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ndomi-Nqeketo/platform_engineer_project.git
    targetRevision: masters
    path: infrastructure/argocd/base/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true