apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: vault
    namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.34.1
      helm:
        releaseName: vault
        valueFiles:
          - $values/vault/values.yaml
          
    - repoURL: https://github.com/Ndomi-Nqeketo/platform_engineer_project.git
      targetRevision: masters
      ref: values
  
    - repoURL: https://github.com/Ndomi-Nqeketo/platform_engineer_project.git
      targetRevision: masters
      path: infrastructure/argocd/base/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true