apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
#  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  
source:
  repoURL: https://github.com/Ndomi-Nqeketo/platform_engineer_project.git
  targetRevision: masters
  path: infrastructure/monitoring/prometheus
  
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
  
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true