apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root
  namespace: minio
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  
  target:
    name: minio-root
    creationPolicy: Owner
  
  data:
    - secretKey: username
      remoteRef:
        key: minio-root
        property: username
    
    - secretKey: password
      remoteRef:
        key: minio-root
        property: password