apiVersion: batch/v1
kind: Job
metadata:
  name: configure-external-secrets-role
  namespace: vault
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      
      containers:
        - name: vault-config
          image: hashicorp/vault:2.0.4
          
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
            
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-root-token
                  key: token
          
          command:
            - /bin/sh
            - -c
            - |
              set -e
              
              vault write auth/kubernetes/role/external-secrets \
                bound_service_account_names="vault-auth" \
                bound_service_account_namespaces="monitoring,masterhub,vault,argocd,minio" \
                policies="external-secrets" \
                ttl="1h"
              
              echo "Vault Kubernetes auth role configured successfully"