apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 20Gi