crds:
  enabled: true
  upgradeJob:
    enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

nodeExporter:
  enabled: false

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    resources:
      requests:
        memory: 128Mi
        cpu: 500m
      limits:
        memory: "2Gi"
        cpu: "2"