apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd
  - prometheus
  - grafana
  - openebs
  - local-path
  - platform
  - vault/application.yaml
  - prometheus-crds
  - masterhub
  - database
  - minio
  - nfs-csi

patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        server.insecure: "true"
  - target:
      kind: Service
      name: argocd-server-metrics
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8083"
  - target:
      kind: Service
      name: argocd-repo-server
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8084"
  - target:
      kind: Service
      name: argocd-applicationset-controller
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
  - target:
      kind: Service
      name: argocd-metrics
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8082"
  - target:
      kind: Service
      name: argocd-notifications-controller-metrics
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9001"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: applicationsets.argoproj.io
    patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: applicationsets.argoproj.io
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
          