apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path
spec:
  project: default
  
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    path: deploy
    targetRevision: master
    
    kustomize:
      patches:
        - target:
            version: v1
            kind: Namespace
            name: local-path-storage
          patch: |-
            - op: add
              path: /metadata/labels/pod-security.kubernetes.io~1enforce
              value: privileged
            - op: add
              path: /metadata/labels/pod-security.kubernetes.io~1audit
              value: privileged
            - op: add
              path: /metadata/labels/pod-security.kubernetes.io~1warn
              value: privileged
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true