apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path
spec:
  project: default
  source:
    repoURL: https://charts.rancher.io
    chart: local-path-provisioner
    targetRevision: 0.0.31
    helm:
      releaseName: local-path
      values: |
        storageClass:
          name: local-path
          defaultClass: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
