apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: vault
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: argocd
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: vault-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: argocd-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: ndomi-local-wildcard
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: ndomi-local-wildcard
        property: tls.key
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: vault
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: vault-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-tls
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: vault-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: ndomi-local-wildcard
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: ndomi-local-wildcard
        property: tls.key
