apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
spec:
  project: default
  sources:
    - repoURL: https://openebs.github.io/dynamic-localpv-provisioner
      chart: localpv-provisioner
      targetRevision: 4.2.0
      helm:
        releaseName: openebs
        valueFiles:
          - $values/infrastructure/argocd/base/openebs/openebs-values.yaml
    - repoURL: https://github.com/Ndomi-Nqeketo/platform_engineer_project.git
      targetRevision: masters
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
