apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: masterhub-postrgres
  namespace: masterhub
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
    
  target:
    name: masterhub-postrgres
    creationPolicy: Owner
    
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: masterhub-postrgres
        property: host
        
    - secretKey: DB_PORT
      remoteRef:
        key: masterhub-postrgres
        property: port
        
    - secretKey: DB_NAME
      remoteRef:
        key: masterhub-postrgres
        property: database
        
    - secretKey: DB_USER
      remoteRef:
        key: masterhub-postrgres
        property: username
        
    - secretKey: DB_PASSWORD
      remoteRef:
        key: masterhub-postrgres
        property: password