apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: godaddy-webhook
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://snowdrop.github.io/godaddy-webhook
    chart: godaddy-webhook
    targetRevision: 0.5.0
    helm:
      releaseName: godaddy-webhook
      values: |
        groupName: acme.masterssoccer.co.za
  
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    syncOptions:
      - CreateNamespace=true